site_name: Orca Tools
nav:
    - Welcome: index.md
    - Orcascript:
        - Syntax Guide: Syntax Guide/index.md
        - Builtins:
            - print: Syntax Guide/builtins/print.md
            - printf: Syntax Guide/builtins/printf.md
            - getenv: Syntax Guide/builtins/getenv.md
            - setenv: Syntax Guide/builtins/setenv.md
            - isfile: Syntax Guide/builtins/isfile.md
            - read: Syntax Guide/builtins/read.md
            - write: Syntax Guide/builtins/write.md
            - mkdir: Syntax Guide/builtins/mkdir.md
            - mkpath: Syntax Guide/builtins/mkpath.md
            - push: Syntax Guide/builtins/push.md

        - Libraries:
            - Template: Syntax Guide/stdlib/template.md
            - SSHClient: Syntax Guide/stdlib/ssh.md
            - Lockbox: Syntax Guide/stdlib/lockbox.md
            - HostInfo: Syntax Guide/stdlib/host.md
            - HTTPClient: Syntax Guide/stdlib/http.md
            - GitClient: Syntax Guide/stdlib/git.md
        
        - Examples:
            - helloworld: Syntax Guide/examples/hello.md

    - Config Management:
        - Intro: Config Management/index.md
        - Declaritive State Definitions: Config Management/state.md
        - Config Management Modules: Config Management/modules.md
    - Task Management:
        - Intro: Task Management/index.md
    - Event Management:
        - Intro: Event Management/index.md
    - Secrets Management:
        - Intro to Lockbox: Secrets Management/index.md
    - Downloads: 
        - Downloads: downloads.md
    
theme:
    icon:
        logo: fontawesome/solid/cog
    name: material
    features:
        - tabs
    custom_dir: overrides
extra_css:
    - stylesheets/extra.css
copyright: "&copy; OrcaTools 2020"
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders: